CREATE TABLE IF NOT EXISTS songs(

    ID VARCHAR(255) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    album VARCHAR(255) NOT NULL,
    duration INT NOT NULL

)